name: CI/CD Pipeline for React & Node.js

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed] # To run the workflow only when the PR is merged
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        script: |
          cd /home/azureuser/sites/TaskSync-react # Change to your directory
          git pull origin master
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd /home/azureuser/sites/TaskSync-react
          npm install
          npm run build
          /home/azureuser/.nvm/versions/node/v18.20.6/bin/pm2 restart all
         